baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Rohit Jain | Software Engineer"
theme = "PaperMod"

[params]
  author = "Rohit Jain"
  description = "Senior Software Engineer | .NET | Azure | System Design Enthusiast"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "Hi, I'm Rohit ðŸ‘‹"
  Content = "I build scalable .NET and cloud-native systems."

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2
